apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-helm-deployment
  namespace: site-helm-lab
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: site-demo
  template:
    metadata:
      labels:
        app: site-demo
    spec:
      containers:
      - name: site-demo-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: site-content
