#!/bin/sh
set -eu

docker_bin=/usr/bin/docker
gateway_label=io.x-k8s.cloud-provider-kind.gateway.name

if [ ! -S /var/run/docker.sock ]; then
  echo "Docker socket is not available" >&2
  exit 1
fi

container_ids="$($docker_bin ps -aq \
  --filter "label=$gateway_label" \
  --filter 'name=^/kindccm-gw-')"

if [ -z "$container_ids" ]; then
  exit 0
fi

for container_id in $container_ids; do
  container_name="$($docker_bin inspect --format '{{.Name}}' "$container_id")"
  gateway_name="$($docker_bin inspect --format '{{index .Config.Labels "io.x-k8s.cloud-provider-kind.gateway.name"}}' "$container_id")"

  case "$container_name" in
    /kindccm-gw-*) ;;
    *)
      echo "Refusing to remove unexpected container: $container_name" >&2
      exit 1
      ;;
  esac

  echo "Removing stale Gateway proxy $container_name for $gateway_name"
done

# Gateway proxy containers are generated by cloud-provider-kind. Recreating
# them after its xDS server starts refreshes the ephemeral xDS port embedded in
# each Envoy bootstrap configuration.
$docker_bin rm -f $container_ids >/dev/null
