services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-1c
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data_for_1c:/var/lib/pgpro/1c-17/data
      - ./1c_role.sql:/docker-entrypoint-initdb.d/1c_role.sql:ro
      - ./pg_hba.conf:/var/lib/pgpro/1c-17/data/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "192.168.56.101:5432:5432"

volumes:
  postgres_data_for_1c:
