---
all:
  children:
    lab_vm:
      hosts:
        lab_vm1:
          ansible_host: 127.0.0.1
      vars:
        ansible_user: vboxuser
        ansible_ssh_private_key_file: /home/vboxuser/.ssh/id_ed25519foransible

    windows_hosts:
      hosts:
        win-devops-01:
          ansible_host: 192.168.56.103
      vars:
        ansible_user: ".\\winops"
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_port: 5985
        ansible_winrm_operation_timeout_sec: 60
        ansible_winrm_read_timeout_sec: 70
        ansible_winrm_server_cert_validation: ignore
        iis_site_name: ansible-lab
        iis_path: C:\Sites\ansible-lab
        iis_pool: ansible-lab-pool
        iis_bind_ip: 192.168.56.103
        iis_port: 8081
        iis_allowed_subnet: 192.168.56.0/24
        iis_url: "http://{{ iis_bind_ip }}:{{ iis_port }}/"
        one_c_user: svc_1c_lab
        one_c_path: C:\1C-lab
        one_c_data_dir: C:\1C-lab\data
        one_c_logs_dir: C:\1C-lab\logs
        one_c_min_free_gib: 10
        one_c_agent_service_name: "1C:Enterprise 8.5 Server Agent"
