- name: Configure lab VM
  hosts: lab_vm1
  gather_facts: true

  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.apt:
        name:
          - curl
          - jq
        state: present
        update_cache: true

    - name: Docker service started and enabled
      service:
        name: docker
        state: started
        enabled: yes
      changed_when: false

