- name: Configure lab VM
  hosts: lab_vm
  gather_facts: true

  tasks:

    - name: Check facts
      ansible.builtin.debug:
        msg: |
          Host: {{ inventory_hostname }}
          OS: {{ ansible_os_family }} {{ ansible_distribution }} {{ ansible_distribution_version }}
          IP: {{ ansible_default_ipv4.address }}
          Gateway: {{ ansible_default_ipv4.gateway | default('N/A') }}


    - name: Docker service started and enabled
      service:
        name: docker
        state: started
        enabled: yes
      changed_when: false

    - name: Check systemctl docker status
      ansible.builtin.command:
        cmd: systemctl status docker.service
      changed_when: false

    - name: Check is docer compose installed
      shell: command -v docker compose >/dev/null 2>&1
      register: is_docker_compose_install
      ignore_errors: yes
      changed_when: false

    - debug: msg="{{ is_docker_compose_install.rc }}" # it returns rc 0 if installed or 127 if not
    - debug: var=is_docker_compose_install


    - name: Show Docker Compose version
      ansible.builtin.command:
        cmd:
          docker compose version
      changed_when: false

    - name: Check HTTP status
      ansible.builtin.uri:
        url: http://192.168.56.101/api/health
        validate_certs: false
        return_content: true
      register: result

    - debug:
        var: result
