name: ansible-validate
on:
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible-validate.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible-validate.yaml'

  workflow_dispatch:

defaults:
  run:
    working-directory: ./ansible

jobs:
  check:
    name: syntax-check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out source
        uses: actions/checkout@v6

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Syntax-Check
        run: |
          ansible-playbook --syntax-check site.yml
          ansible-playbook --syntax-check verify.yml
          ansible-playbook --syntax-check site-backup.yml
          ansible-playbook --syntax-check verify-logrotate.yaml

  deploy:
    name: Deploy
    runs-on: self-hosted
    timeout-minutes: 15
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: syntax-check

    steps:
      - uses: actions/checkout@v6
      - name: Set up SSH
        run: |
          echo "${{ secrets.SSHPRIVATEKEY }}" > private_key.pem
          chmod 600 private_key.pem
      - name: Run Ansible playbook
        run: ansible-playbook verify.yml -i inventory.yaml
        run: ansible-playbook verify-logrotate.yml -i inventory.yaml
