name: windows-service
on:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: ./ansible

jobs:
  windows-service:
    name: windows-service
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
    - name: Check out source
      uses: actions/checkout@v6


    - name: Run with temp vault file (secure)
      env:
        VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
      run: |

        tmp_file=$(mktemp --tmpdir vault_pass_XXXXXX)
        echo "$VAULT_PASSWORD" > "$tmp_file"
        chmod 600 "$tmp_file"          # <-- вот так ставим строгие права
        trap "rm -f '$tmp_file'" EXIT

        /home/vboxuser/.local/bin/ansible-playbook \
          -i inventory.yml \
          windows-service.yml \
          --check \
          --vault-password-file="$tmp_file"

    - name: Cleanup secrets
      if: always()
      run: |
        rm -f /tmp/vault_pass.txt
