name: opentofu-apply
on:
  workflow_dispatch:

concurrency:
  group: opentofu
  cancel-in-progress: false
defaults:
  run:
    working-directory: ./opentofu/docker-lab
jobs:
  tofu-apply:
    name: plan-check
    runs-on: self-hosted
    timeout-minutes: 10
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Check branch is main
        run: |
          if [ "$GITHUB_REF_NAME" != "main" ]; then
            echo "Ошибка: разрешено запускать только из ветки main."
            echo "Текущая (выбранная) ветка: ${{ github.ref_name }}"
            exit 1
          fi

      - name: Check out source
        uses: actions/checkout@v6
      - name: Check all config and format
        run: |
          tofu --version
          tofu init
          tofu state list
          tofu plan -detailed-exitcode
          tofu fmt -check -recursive
          tofu validate

      - name: Build Plan
        run: |
          echo "Generating plan..."
          tofu plan -out=tfplan
          PLAN_EXIT_CODE=$?

          if [ "$PLAN_EXIT_CODE" -eq 0 ]; then
            echo "::notice::No changes detected (exit code 0)."
          elif [ "$PLAN_EXIT_CODE" -eq 2 ]; then
            echo "::notice::Plan has changes (exit code 2). Review before applying."
            # Здесь НЕ делаем exit 1 — мы хотим, чтобы job продолжил работу, если дальше будет apply
          else
            echo "::error::Plan failed with unexpected error (exit code $PLAN_EXIT_CODE)."
            exit 1
          fi

      - name: Apply Saved Plan
        run: tofu apply -auto-approve tfplan

      - name: Cleanup Plan File
        if: always()
        run: rm -f tfplan

